---
  # What command to be used for running a command (This will also be used to run the executor)
  shell: "zsh"

  # What command to be used to execute an application
  executor: "hyprctl dispatch exec"

  # How many items will the search algorithm find?
  max_search: 30

  # How many items with the renderer draw (works with scrolling)
  max_render: 30

  # Logging is an in-terminal solution to what is being run. Not a error thing
  # So using an exit on each means not being able to read the logs
  max_log: 30

  # What events are run no matter what you are doing
  # These are always run after the regular event
  each:
    - exit

  # Set Custom Keybindings.
  # All shown here are the defaults.
  binds:
    # Show the logs
    logs:
      - shift-L

    # Edit the search 
    insert:
      - i

    # Go back to normal mode
    normal:
      - esc
      - q

    # Exits the program (in normal mode)
    quit:
      - esc
      - q

    # Run the selected target (does nothing on folders)
    run:
      - enter

    # Clears the search bar (in normal mode)
    clear:
      - c

    # Moves selection up (in normal mode)
    up:
      - up
      - k

    # Moves selection down (in normal mode)
    down:
      - down
      - j

    # Goes up a level in the path (in normal mode)
    exit:
      - left
      - h

    # Enters the hovered folder
    enter:
      - right
      - l
      - enter


  # Each Possible Event
  entries:
    # An Example event that will run ghostty using the executor
    # This will then exit, as the `each` section contains an exit event
    - !entry
      icon: ""
      name: "Ghostty"
      icon_color: green
      events:
        - !exec ghostty

    # An Example that will drop to shell, run a command, then get the output.
    # This could be some "sub-menu", or a calculator/ai or whatever
    # For this situation, it'll run yazi, and do nothing with it
    - !entry
      icon: "Y"
      name: "Yazi"
      icon_color: yellow
      ignore_each: true
      events:
        - !shell yazi

    # An Example Folder, which is a way of categorizing your apps
    # These are not visible when searching! They are simply there
    # to make it easier to navigate without searching.
    - !folder
      name: "Hello"
      entries:
        # An Example event that will send a notification saying Hello, World.
        # This example will ignore the `each` calls, so it won't exit
        - !entry
          icon: "H"
          name: "Hello, World!"
          icon_color: blue
          ignore_each: true
          events:
            - !cmd notify-send -e "Hello, World!"
 
